// Code generated by ent, DO NOT EDIT.

package family

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/afv1/sims-tree/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Surname applies equality check predicate on the "surname" field. It's identical to SurnameEQ.
func Surname(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSurname), v))
	})
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDescription), v))
	})
}

// LogoResource applies equality check predicate on the "logo_resource" field. It's identical to LogoResourceEQ.
func LogoResource(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLogoResource), v))
	})
}

// SurnameEQ applies the EQ predicate on the "surname" field.
func SurnameEQ(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSurname), v))
	})
}

// SurnameNEQ applies the NEQ predicate on the "surname" field.
func SurnameNEQ(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSurname), v))
	})
}

// SurnameIn applies the In predicate on the "surname" field.
func SurnameIn(vs ...string) predicate.Family {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldSurname), v...))
	})
}

// SurnameNotIn applies the NotIn predicate on the "surname" field.
func SurnameNotIn(vs ...string) predicate.Family {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldSurname), v...))
	})
}

// SurnameGT applies the GT predicate on the "surname" field.
func SurnameGT(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSurname), v))
	})
}

// SurnameGTE applies the GTE predicate on the "surname" field.
func SurnameGTE(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSurname), v))
	})
}

// SurnameLT applies the LT predicate on the "surname" field.
func SurnameLT(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSurname), v))
	})
}

// SurnameLTE applies the LTE predicate on the "surname" field.
func SurnameLTE(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSurname), v))
	})
}

// SurnameContains applies the Contains predicate on the "surname" field.
func SurnameContains(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSurname), v))
	})
}

// SurnameHasPrefix applies the HasPrefix predicate on the "surname" field.
func SurnameHasPrefix(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSurname), v))
	})
}

// SurnameHasSuffix applies the HasSuffix predicate on the "surname" field.
func SurnameHasSuffix(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSurname), v))
	})
}

// SurnameEqualFold applies the EqualFold predicate on the "surname" field.
func SurnameEqualFold(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSurname), v))
	})
}

// SurnameContainsFold applies the ContainsFold predicate on the "surname" field.
func SurnameContainsFold(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSurname), v))
	})
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDescription), v))
	})
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDescription), v))
	})
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Family {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldDescription), v...))
	})
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Family {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldDescription), v...))
	})
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDescription), v))
	})
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDescription), v))
	})
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDescription), v))
	})
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDescription), v))
	})
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldDescription), v))
	})
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldDescription), v))
	})
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldDescription), v))
	})
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldDescription), v))
	})
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldDescription), v))
	})
}

// LogoResourceEQ applies the EQ predicate on the "logo_resource" field.
func LogoResourceEQ(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLogoResource), v))
	})
}

// LogoResourceNEQ applies the NEQ predicate on the "logo_resource" field.
func LogoResourceNEQ(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldLogoResource), v))
	})
}

// LogoResourceIn applies the In predicate on the "logo_resource" field.
func LogoResourceIn(vs ...string) predicate.Family {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldLogoResource), v...))
	})
}

// LogoResourceNotIn applies the NotIn predicate on the "logo_resource" field.
func LogoResourceNotIn(vs ...string) predicate.Family {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldLogoResource), v...))
	})
}

// LogoResourceGT applies the GT predicate on the "logo_resource" field.
func LogoResourceGT(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldLogoResource), v))
	})
}

// LogoResourceGTE applies the GTE predicate on the "logo_resource" field.
func LogoResourceGTE(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldLogoResource), v))
	})
}

// LogoResourceLT applies the LT predicate on the "logo_resource" field.
func LogoResourceLT(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldLogoResource), v))
	})
}

// LogoResourceLTE applies the LTE predicate on the "logo_resource" field.
func LogoResourceLTE(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldLogoResource), v))
	})
}

// LogoResourceContains applies the Contains predicate on the "logo_resource" field.
func LogoResourceContains(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldLogoResource), v))
	})
}

// LogoResourceHasPrefix applies the HasPrefix predicate on the "logo_resource" field.
func LogoResourceHasPrefix(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldLogoResource), v))
	})
}

// LogoResourceHasSuffix applies the HasSuffix predicate on the "logo_resource" field.
func LogoResourceHasSuffix(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldLogoResource), v))
	})
}

// LogoResourceEqualFold applies the EqualFold predicate on the "logo_resource" field.
func LogoResourceEqualFold(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldLogoResource), v))
	})
}

// LogoResourceContainsFold applies the ContainsFold predicate on the "logo_resource" field.
func LogoResourceContainsFold(v string) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldLogoResource), v))
	})
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(OwnerTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(OwnerInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRelatives applies the HasEdge predicate on the "relatives" edge.
func HasRelatives() predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RelativesTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RelativesTable, RelativesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelativesWith applies the HasEdge predicate on the "relatives" edge with a given conditions (other predicates).
func HasRelativesWith(preds ...predicate.Relative) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RelativesInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RelativesTable, RelativesColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Family) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Family) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Family) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		p(s.Not())
	})
}
