// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FamiliesColumns holds the columns for the "families" table.
	FamiliesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "surname", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "logo_resource", Type: field.TypeString},
		{Name: "user_families", Type: field.TypeInt, Nullable: true},
	}
	// FamiliesTable holds the schema information for the "families" table.
	FamiliesTable = &schema.Table{
		Name:       "families",
		Columns:    FamiliesColumns,
		PrimaryKey: []*schema.Column{FamiliesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "families_users_families",
				Columns:    []*schema.Column{FamiliesColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// RelativesColumns holds the columns for the "relatives" table.
	RelativesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "avatar_resource", Type: field.TypeString},
		{Name: "family_relatives", Type: field.TypeInt, Nullable: true},
	}
	// RelativesTable holds the schema information for the "relatives" table.
	RelativesTable = &schema.Table{
		Name:       "relatives",
		Columns:    RelativesColumns,
		PrimaryKey: []*schema.Column{RelativesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "relatives_families_relatives",
				Columns:    []*schema.Column{RelativesColumns[4]},
				RefColumns: []*schema.Column{FamiliesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "login", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "comment", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FamiliesTable,
		RelativesTable,
		UsersTable,
	}
)

func init() {
	FamiliesTable.ForeignKeys[0].RefTable = UsersTable
	RelativesTable.ForeignKeys[0].RefTable = FamiliesTable
}
