// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"github.com/afv1/sims-tree/ent/migrate"

	"github.com/afv1/sims-tree/ent/family"
	"github.com/afv1/sims-tree/ent/relative"
	"github.com/afv1/sims-tree/ent/user"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Family is the client for interacting with the Family builders.
	Family *FamilyClient
	// Relative is the client for interacting with the Relative builders.
	Relative *RelativeClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Family = NewFamilyClient(c.config)
	c.Relative = NewRelativeClient(c.config)
	c.User = NewUserClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:      ctx,
		config:   cfg,
		Family:   NewFamilyClient(cfg),
		Relative: NewRelativeClient(cfg),
		User:     NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:      ctx,
		config:   cfg,
		Family:   NewFamilyClient(cfg),
		Relative: NewRelativeClient(cfg),
		User:     NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Family.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Family.Use(hooks...)
	c.Relative.Use(hooks...)
	c.User.Use(hooks...)
}

// FamilyClient is a client for the Family schema.
type FamilyClient struct {
	config
}

// NewFamilyClient returns a client for the Family from the given config.
func NewFamilyClient(c config) *FamilyClient {
	return &FamilyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `family.Hooks(f(g(h())))`.
func (c *FamilyClient) Use(hooks ...Hook) {
	c.hooks.Family = append(c.hooks.Family, hooks...)
}

// Create returns a builder for creating a Family entity.
func (c *FamilyClient) Create() *FamilyCreate {
	mutation := newFamilyMutation(c.config, OpCreate)
	return &FamilyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Family entities.
func (c *FamilyClient) CreateBulk(builders ...*FamilyCreate) *FamilyCreateBulk {
	return &FamilyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Family.
func (c *FamilyClient) Update() *FamilyUpdate {
	mutation := newFamilyMutation(c.config, OpUpdate)
	return &FamilyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FamilyClient) UpdateOne(f *Family) *FamilyUpdateOne {
	mutation := newFamilyMutation(c.config, OpUpdateOne, withFamily(f))
	return &FamilyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FamilyClient) UpdateOneID(id int) *FamilyUpdateOne {
	mutation := newFamilyMutation(c.config, OpUpdateOne, withFamilyID(id))
	return &FamilyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Family.
func (c *FamilyClient) Delete() *FamilyDelete {
	mutation := newFamilyMutation(c.config, OpDelete)
	return &FamilyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FamilyClient) DeleteOne(f *Family) *FamilyDeleteOne {
	return c.DeleteOneID(f.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FamilyClient) DeleteOneID(id int) *FamilyDeleteOne {
	builder := c.Delete().Where(family.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FamilyDeleteOne{builder}
}

// Query returns a query builder for Family.
func (c *FamilyClient) Query() *FamilyQuery {
	return &FamilyQuery{
		config: c.config,
	}
}

// Get returns a Family entity by its id.
func (c *FamilyClient) Get(ctx context.Context, id int) (*Family, error) {
	return c.Query().Where(family.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FamilyClient) GetX(ctx context.Context, id int) *Family {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryOwner queries the owner edge of a Family.
func (c *FamilyClient) QueryOwner(f *Family) *UserQuery {
	query := &UserQuery{config: c.config}
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := f.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(family.Table, family.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, family.OwnerTable, family.OwnerColumn),
		)
		fromV = sqlgraph.Neighbors(f.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryRelatives queries the relatives edge of a Family.
func (c *FamilyClient) QueryRelatives(f *Family) *RelativeQuery {
	query := &RelativeQuery{config: c.config}
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := f.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(family.Table, family.FieldID, id),
			sqlgraph.To(relative.Table, relative.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, family.RelativesTable, family.RelativesColumn),
		)
		fromV = sqlgraph.Neighbors(f.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *FamilyClient) Hooks() []Hook {
	return c.hooks.Family
}

// RelativeClient is a client for the Relative schema.
type RelativeClient struct {
	config
}

// NewRelativeClient returns a client for the Relative from the given config.
func NewRelativeClient(c config) *RelativeClient {
	return &RelativeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `relative.Hooks(f(g(h())))`.
func (c *RelativeClient) Use(hooks ...Hook) {
	c.hooks.Relative = append(c.hooks.Relative, hooks...)
}

// Create returns a builder for creating a Relative entity.
func (c *RelativeClient) Create() *RelativeCreate {
	mutation := newRelativeMutation(c.config, OpCreate)
	return &RelativeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Relative entities.
func (c *RelativeClient) CreateBulk(builders ...*RelativeCreate) *RelativeCreateBulk {
	return &RelativeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Relative.
func (c *RelativeClient) Update() *RelativeUpdate {
	mutation := newRelativeMutation(c.config, OpUpdate)
	return &RelativeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RelativeClient) UpdateOne(r *Relative) *RelativeUpdateOne {
	mutation := newRelativeMutation(c.config, OpUpdateOne, withRelative(r))
	return &RelativeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RelativeClient) UpdateOneID(id int) *RelativeUpdateOne {
	mutation := newRelativeMutation(c.config, OpUpdateOne, withRelativeID(id))
	return &RelativeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Relative.
func (c *RelativeClient) Delete() *RelativeDelete {
	mutation := newRelativeMutation(c.config, OpDelete)
	return &RelativeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RelativeClient) DeleteOne(r *Relative) *RelativeDeleteOne {
	return c.DeleteOneID(r.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RelativeClient) DeleteOneID(id int) *RelativeDeleteOne {
	builder := c.Delete().Where(relative.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RelativeDeleteOne{builder}
}

// Query returns a query builder for Relative.
func (c *RelativeClient) Query() *RelativeQuery {
	return &RelativeQuery{
		config: c.config,
	}
}

// Get returns a Relative entity by its id.
func (c *RelativeClient) Get(ctx context.Context, id int) (*Relative, error) {
	return c.Query().Where(relative.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RelativeClient) GetX(ctx context.Context, id int) *Relative {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryFamilies queries the families edge of a Relative.
func (c *RelativeClient) QueryFamilies(r *Relative) *FamilyQuery {
	query := &FamilyQuery{config: c.config}
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := r.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(relative.Table, relative.FieldID, id),
			sqlgraph.To(family.Table, family.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, relative.FamiliesTable, relative.FamiliesColumn),
		)
		fromV = sqlgraph.Neighbors(r.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RelativeClient) Hooks() []Hook {
	return c.hooks.Relative
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryFamilies queries the families edge of a User.
func (c *UserClient) QueryFamilies(u *User) *FamilyQuery {
	query := &FamilyQuery{config: c.config}
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(family.Table, family.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.FamiliesTable, user.FamiliesColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}
