// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/afv1/sims-tree/ent/family"
	"github.com/afv1/sims-tree/ent/relative"
	"github.com/afv1/sims-tree/ent/user"
)

// FamilyCreate is the builder for creating a Family entity.
type FamilyCreate struct {
	config
	mutation *FamilyMutation
	hooks    []Hook
}

// SetSurname sets the "surname" field.
func (fc *FamilyCreate) SetSurname(s string) *FamilyCreate {
	fc.mutation.SetSurname(s)
	return fc
}

// SetDescription sets the "description" field.
func (fc *FamilyCreate) SetDescription(s string) *FamilyCreate {
	fc.mutation.SetDescription(s)
	return fc
}

// SetLogoResource sets the "logo_resource" field.
func (fc *FamilyCreate) SetLogoResource(s string) *FamilyCreate {
	fc.mutation.SetLogoResource(s)
	return fc
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (fc *FamilyCreate) SetOwnerID(id int) *FamilyCreate {
	fc.mutation.SetOwnerID(id)
	return fc
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (fc *FamilyCreate) SetNillableOwnerID(id *int) *FamilyCreate {
	if id != nil {
		fc = fc.SetOwnerID(*id)
	}
	return fc
}

// SetOwner sets the "owner" edge to the User entity.
func (fc *FamilyCreate) SetOwner(u *User) *FamilyCreate {
	return fc.SetOwnerID(u.ID)
}

// AddRelativeIDs adds the "relatives" edge to the Relative entity by IDs.
func (fc *FamilyCreate) AddRelativeIDs(ids ...int) *FamilyCreate {
	fc.mutation.AddRelativeIDs(ids...)
	return fc
}

// AddRelatives adds the "relatives" edges to the Relative entity.
func (fc *FamilyCreate) AddRelatives(r ...*Relative) *FamilyCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return fc.AddRelativeIDs(ids...)
}

// Mutation returns the FamilyMutation object of the builder.
func (fc *FamilyCreate) Mutation() *FamilyMutation {
	return fc.mutation
}

// Save creates the Family in the database.
func (fc *FamilyCreate) Save(ctx context.Context) (*Family, error) {
	var (
		err  error
		node *Family
	)
	if len(fc.hooks) == 0 {
		if err = fc.check(); err != nil {
			return nil, err
		}
		node, err = fc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FamilyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = fc.check(); err != nil {
				return nil, err
			}
			fc.mutation = mutation
			if node, err = fc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(fc.hooks) - 1; i >= 0; i-- {
			if fc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = fc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, fc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Family)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from FamilyMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (fc *FamilyCreate) SaveX(ctx context.Context) *Family {
	v, err := fc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fc *FamilyCreate) Exec(ctx context.Context) error {
	_, err := fc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fc *FamilyCreate) ExecX(ctx context.Context) {
	if err := fc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fc *FamilyCreate) check() error {
	if _, ok := fc.mutation.Surname(); !ok {
		return &ValidationError{Name: "surname", err: errors.New(`ent: missing required field "Family.surname"`)}
	}
	if _, ok := fc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Family.description"`)}
	}
	if _, ok := fc.mutation.LogoResource(); !ok {
		return &ValidationError{Name: "logo_resource", err: errors.New(`ent: missing required field "Family.logo_resource"`)}
	}
	return nil
}

func (fc *FamilyCreate) sqlSave(ctx context.Context) (*Family, error) {
	_node, _spec := fc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (fc *FamilyCreate) createSpec() (*Family, *sqlgraph.CreateSpec) {
	var (
		_node = &Family{config: fc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: family.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: family.FieldID,
			},
		}
	)
	if value, ok := fc.mutation.Surname(); ok {
		_spec.SetField(family.FieldSurname, field.TypeString, value)
		_node.Surname = value
	}
	if value, ok := fc.mutation.Description(); ok {
		_spec.SetField(family.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := fc.mutation.LogoResource(); ok {
		_spec.SetField(family.FieldLogoResource, field.TypeString, value)
		_node.LogoResource = &value
	}
	if nodes := fc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   family.OwnerTable,
			Columns: []string{family.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_families = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := fc.mutation.RelativesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   family.RelativesTable,
			Columns: []string{family.RelativesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: relative.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FamilyCreateBulk is the builder for creating many Family entities in bulk.
type FamilyCreateBulk struct {
	config
	builders []*FamilyCreate
}

// Save creates the Family entities in the database.
func (fcb *FamilyCreateBulk) Save(ctx context.Context) ([]*Family, error) {
	specs := make([]*sqlgraph.CreateSpec, len(fcb.builders))
	nodes := make([]*Family, len(fcb.builders))
	mutators := make([]Mutator, len(fcb.builders))
	for i := range fcb.builders {
		func(i int, root context.Context) {
			builder := fcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FamilyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fcb *FamilyCreateBulk) SaveX(ctx context.Context) []*Family {
	v, err := fcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fcb *FamilyCreateBulk) Exec(ctx context.Context) error {
	_, err := fcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fcb *FamilyCreateBulk) ExecX(ctx context.Context) {
	if err := fcb.Exec(ctx); err != nil {
		panic(err)
	}
}
