// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/afv1/sims-tree/ent/family"
	"github.com/afv1/sims-tree/ent/predicate"
	"github.com/afv1/sims-tree/ent/relative"
)

// RelativeUpdate is the builder for updating Relative entities.
type RelativeUpdate struct {
	config
	hooks    []Hook
	mutation *RelativeMutation
}

// Where appends a list predicates to the RelativeUpdate builder.
func (ru *RelativeUpdate) Where(ps ...predicate.Relative) *RelativeUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetName sets the "name" field.
func (ru *RelativeUpdate) SetName(s string) *RelativeUpdate {
	ru.mutation.SetName(s)
	return ru
}

// SetDescription sets the "description" field.
func (ru *RelativeUpdate) SetDescription(s string) *RelativeUpdate {
	ru.mutation.SetDescription(s)
	return ru
}

// SetAvatarResource sets the "avatar_resource" field.
func (ru *RelativeUpdate) SetAvatarResource(s string) *RelativeUpdate {
	ru.mutation.SetAvatarResource(s)
	return ru
}

// SetFamiliesID sets the "families" edge to the Family entity by ID.
func (ru *RelativeUpdate) SetFamiliesID(id int) *RelativeUpdate {
	ru.mutation.SetFamiliesID(id)
	return ru
}

// SetNillableFamiliesID sets the "families" edge to the Family entity by ID if the given value is not nil.
func (ru *RelativeUpdate) SetNillableFamiliesID(id *int) *RelativeUpdate {
	if id != nil {
		ru = ru.SetFamiliesID(*id)
	}
	return ru
}

// SetFamilies sets the "families" edge to the Family entity.
func (ru *RelativeUpdate) SetFamilies(f *Family) *RelativeUpdate {
	return ru.SetFamiliesID(f.ID)
}

// Mutation returns the RelativeMutation object of the builder.
func (ru *RelativeUpdate) Mutation() *RelativeMutation {
	return ru.mutation
}

// ClearFamilies clears the "families" edge to the Family entity.
func (ru *RelativeUpdate) ClearFamilies() *RelativeUpdate {
	ru.mutation.ClearFamilies()
	return ru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RelativeUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ru.hooks) == 0 {
		if err = ru.check(); err != nil {
			return 0, err
		}
		affected, err = ru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RelativeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ru.check(); err != nil {
				return 0, err
			}
			ru.mutation = mutation
			affected, err = ru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ru.hooks) - 1; i >= 0; i-- {
			if ru.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RelativeUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RelativeUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RelativeUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ru *RelativeUpdate) check() error {
	if v, ok := ru.mutation.Name(); ok {
		if err := relative.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Relative.name": %w`, err)}
		}
	}
	return nil
}

func (ru *RelativeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   relative.Table,
			Columns: relative.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: relative.FieldID,
			},
		},
	}
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.Name(); ok {
		_spec.SetField(relative.FieldName, field.TypeString, value)
	}
	if value, ok := ru.mutation.Description(); ok {
		_spec.SetField(relative.FieldDescription, field.TypeString, value)
	}
	if value, ok := ru.mutation.AvatarResource(); ok {
		_spec.SetField(relative.FieldAvatarResource, field.TypeString, value)
	}
	if ru.mutation.FamiliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relative.FamiliesTable,
			Columns: []string{relative.FamiliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: family.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.FamiliesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relative.FamiliesTable,
			Columns: []string{relative.FamiliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: family.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relative.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// RelativeUpdateOne is the builder for updating a single Relative entity.
type RelativeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RelativeMutation
}

// SetName sets the "name" field.
func (ruo *RelativeUpdateOne) SetName(s string) *RelativeUpdateOne {
	ruo.mutation.SetName(s)
	return ruo
}

// SetDescription sets the "description" field.
func (ruo *RelativeUpdateOne) SetDescription(s string) *RelativeUpdateOne {
	ruo.mutation.SetDescription(s)
	return ruo
}

// SetAvatarResource sets the "avatar_resource" field.
func (ruo *RelativeUpdateOne) SetAvatarResource(s string) *RelativeUpdateOne {
	ruo.mutation.SetAvatarResource(s)
	return ruo
}

// SetFamiliesID sets the "families" edge to the Family entity by ID.
func (ruo *RelativeUpdateOne) SetFamiliesID(id int) *RelativeUpdateOne {
	ruo.mutation.SetFamiliesID(id)
	return ruo
}

// SetNillableFamiliesID sets the "families" edge to the Family entity by ID if the given value is not nil.
func (ruo *RelativeUpdateOne) SetNillableFamiliesID(id *int) *RelativeUpdateOne {
	if id != nil {
		ruo = ruo.SetFamiliesID(*id)
	}
	return ruo
}

// SetFamilies sets the "families" edge to the Family entity.
func (ruo *RelativeUpdateOne) SetFamilies(f *Family) *RelativeUpdateOne {
	return ruo.SetFamiliesID(f.ID)
}

// Mutation returns the RelativeMutation object of the builder.
func (ruo *RelativeUpdateOne) Mutation() *RelativeMutation {
	return ruo.mutation
}

// ClearFamilies clears the "families" edge to the Family entity.
func (ruo *RelativeUpdateOne) ClearFamilies() *RelativeUpdateOne {
	ruo.mutation.ClearFamilies()
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RelativeUpdateOne) Select(field string, fields ...string) *RelativeUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Relative entity.
func (ruo *RelativeUpdateOne) Save(ctx context.Context) (*Relative, error) {
	var (
		err  error
		node *Relative
	)
	if len(ruo.hooks) == 0 {
		if err = ruo.check(); err != nil {
			return nil, err
		}
		node, err = ruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RelativeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ruo.check(); err != nil {
				return nil, err
			}
			ruo.mutation = mutation
			node, err = ruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ruo.hooks) - 1; i >= 0; i-- {
			if ruo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ruo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, ruo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Relative)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from RelativeMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RelativeUpdateOne) SaveX(ctx context.Context) *Relative {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RelativeUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RelativeUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ruo *RelativeUpdateOne) check() error {
	if v, ok := ruo.mutation.Name(); ok {
		if err := relative.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Relative.name": %w`, err)}
		}
	}
	return nil
}

func (ruo *RelativeUpdateOne) sqlSave(ctx context.Context) (_node *Relative, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   relative.Table,
			Columns: relative.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: relative.FieldID,
			},
		},
	}
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Relative.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, relative.FieldID)
		for _, f := range fields {
			if !relative.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != relative.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.Name(); ok {
		_spec.SetField(relative.FieldName, field.TypeString, value)
	}
	if value, ok := ruo.mutation.Description(); ok {
		_spec.SetField(relative.FieldDescription, field.TypeString, value)
	}
	if value, ok := ruo.mutation.AvatarResource(); ok {
		_spec.SetField(relative.FieldAvatarResource, field.TypeString, value)
	}
	if ruo.mutation.FamiliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relative.FamiliesTable,
			Columns: []string{relative.FamiliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: family.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.FamiliesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relative.FamiliesTable,
			Columns: []string{relative.FamiliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: family.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Relative{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relative.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
