// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/afv1/sims-tree/ent/relative"
	"github.com/afv1/sims-tree/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	relativeFields := schema.Relative{}.Fields()
	_ = relativeFields
	// relativeDescName is the schema descriptor for name field.
	relativeDescName := relativeFields[0].Descriptor()
	// relative.NameValidator is a validator for the "name" field. It is called by the builders before save.
	relative.NameValidator = relativeDescName.Validators[0].(func(string) error)
}
