// Code generated by ent, DO NOT EDIT.

package relative

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/afv1/sims-tree/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDescription), v))
	})
}

// AvatarResource applies equality check predicate on the "avatar_resource" field. It's identical to AvatarResourceEQ.
func AvatarResource(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAvatarResource), v))
	})
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldName), v))
	})
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Relative {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldName), v...))
	})
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Relative {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldName), v...))
	})
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldName), v))
	})
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldName), v))
	})
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldName), v))
	})
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldName), v))
	})
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldName), v))
	})
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldName), v))
	})
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldName), v))
	})
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldName), v))
	})
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldName), v))
	})
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDescription), v))
	})
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDescription), v))
	})
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Relative {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldDescription), v...))
	})
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Relative {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldDescription), v...))
	})
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDescription), v))
	})
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDescription), v))
	})
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDescription), v))
	})
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDescription), v))
	})
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldDescription), v))
	})
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldDescription), v))
	})
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldDescription), v))
	})
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldDescription), v))
	})
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldDescription), v))
	})
}

// AvatarResourceEQ applies the EQ predicate on the "avatar_resource" field.
func AvatarResourceEQ(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAvatarResource), v))
	})
}

// AvatarResourceNEQ applies the NEQ predicate on the "avatar_resource" field.
func AvatarResourceNEQ(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldAvatarResource), v))
	})
}

// AvatarResourceIn applies the In predicate on the "avatar_resource" field.
func AvatarResourceIn(vs ...string) predicate.Relative {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldAvatarResource), v...))
	})
}

// AvatarResourceNotIn applies the NotIn predicate on the "avatar_resource" field.
func AvatarResourceNotIn(vs ...string) predicate.Relative {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldAvatarResource), v...))
	})
}

// AvatarResourceGT applies the GT predicate on the "avatar_resource" field.
func AvatarResourceGT(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldAvatarResource), v))
	})
}

// AvatarResourceGTE applies the GTE predicate on the "avatar_resource" field.
func AvatarResourceGTE(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldAvatarResource), v))
	})
}

// AvatarResourceLT applies the LT predicate on the "avatar_resource" field.
func AvatarResourceLT(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldAvatarResource), v))
	})
}

// AvatarResourceLTE applies the LTE predicate on the "avatar_resource" field.
func AvatarResourceLTE(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldAvatarResource), v))
	})
}

// AvatarResourceContains applies the Contains predicate on the "avatar_resource" field.
func AvatarResourceContains(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldAvatarResource), v))
	})
}

// AvatarResourceHasPrefix applies the HasPrefix predicate on the "avatar_resource" field.
func AvatarResourceHasPrefix(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldAvatarResource), v))
	})
}

// AvatarResourceHasSuffix applies the HasSuffix predicate on the "avatar_resource" field.
func AvatarResourceHasSuffix(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldAvatarResource), v))
	})
}

// AvatarResourceEqualFold applies the EqualFold predicate on the "avatar_resource" field.
func AvatarResourceEqualFold(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldAvatarResource), v))
	})
}

// AvatarResourceContainsFold applies the ContainsFold predicate on the "avatar_resource" field.
func AvatarResourceContainsFold(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldAvatarResource), v))
	})
}

// HasFamilies applies the HasEdge predicate on the "families" edge.
func HasFamilies() predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(FamiliesTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FamiliesTable, FamiliesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFamiliesWith applies the HasEdge predicate on the "families" edge with a given conditions (other predicates).
func HasFamiliesWith(preds ...predicate.Family) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(FamiliesInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FamiliesTable, FamiliesColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Relative) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Relative) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Relative) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		p(s.Not())
	})
}
