// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Family is the predicate function for family builders.
type Family func(*sql.Selector)

// Relative is the predicate function for relative builders.
type Relative func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
